# Generated by Django 3.2.4 on 2021-06-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='occupants_count',
        ),
    ]
